import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
class FeedBack extends JFrame implements ActionListener{
String userID;
JLabel label, label1, label2, label3, label4, label5, label6, label7, label8, label9, label10, label11,msg;
JTextField t1, t2, t3, t4 ;
JComboBox c1, c2, c3, c4, c5 ,c6,cater;
JTextArea A,B ;
JCheckBox box ;
JButton B1, B2;                     
FeedBack(){
JFrame Feedback=new JFrame();
// ImageIcon framebg=new ImageIcon("fortbg.jpg");
// C.setContentPane(new JLabel(framebg));
setTitle("Feedback Form") ;
setSize(3000,3000);
setDefaultCloseOperation( EXIT_ON_CLOSE) ;
Container C = getContentPane() ;
C.setLayout(null) ;
C.setBackground(Color.YELLOW);
Font f1 = new Font("Castellar ", Font.BOLD,20) ;
Font f2 = new Font(" Arial Black ", Font.BOLD,16) ;
Font f3 = new Font(" Arial Black ", Font.BOLD,18) ;
label = new JLabel("Feedback ");
label.setFont(new Font("Castellar ", Font.BOLD,60)) ;
label.setForeground(Color.BLACK) ;
label.setBounds(10,40,900,90) ;
C.add(label) ;
label1 = new JLabel(" CUSTOMER SERVICE ") ;
label1.setFont(f2) ;
label1.setForeground(Color.BLUE) ;
label1.setBounds(40,140,200,20) ;
C.add(label1) ;
String[] values1 = {"*" , "**", "***", "****", "*****"};
c1 = new JComboBox(values1) ;
c1.setForeground(Color.PINK) ;
c1.setBounds(340,140,200,20) ;
C.add(c1) ;
label2 = new JLabel(" DECORATION ") ;
label2.setFont(f2) ;
label2.setForeground(Color.BLUE) ;
label2.setBounds(40,170,200,20) ;
C.add(label2) ;
String[] values2 = {"Excellent" , "Very Good", "Good", "Average", "Poor"};
c2 = new JComboBox(values2) ;
c2.setForeground(Color.PINK) ;
c2.setBounds(340,170,200,20) ;
C.add(c2) ;
label3= new JLabel(" DECORATION (Your opinions) ") ;
label3.setFont(f2) ;
label3.setForeground(Color.BLUE) ;
label3.setBounds(40,200,300,20) ;
C.add(label3) ;
t1 = new JTextField() ;
t1.setFont(f2) ;
t1.setForeground(Color.PINK) ;
t1.setBounds(340,200,200,20) ;
C.add(t1) ;
label4 = new JLabel("PUNCTUALITY") ;
label4.setFont(f2) ;
label4.setForeground(Color.BLUE) ;
label4.setBounds(40,230,200,20) ;
C.add(label4) ;
String[] values3= {"Excellent" , "Very Good", "Good", "Average", "Poor"};
c3 = new JComboBox(values3) ;
c3.setForeground(Color.PINK) ;
c3.setBounds(340,230,200,20) ;
C.add(c3) ;
label5 = new JLabel("CATERING SERVICE") ;
label5.setFont(f2) ;
label5.setForeground(Color.BLUE) ;
label5.setBounds(40,260,200,20) ;
C.add(label5) ;
cater = new JComboBox(values3) ;
// t2.setText(" Enter which Food Items you attracted most???? ") ;
cater.setFont(f2) ;
cater.setForeground(Color.PINK) ;
cater.setBounds(340,260,200,20) ;
C.add(cater) ;
label6 = new JLabel("CATERING SERVICE (Your opinion)") ;
label6.setFont(f2) ;
label6.setForeground(Color.BLUE) ;
label6.setBounds(40,290,300,20) ;
C.add(label6) ;
t3 = new JTextField() ;
// t3.setText(" Enter which Regional thalis you like most???? ") ;
t3.setFont(f2) ;
t3.setForeground(Color.PINK) ;
t3.setBounds(340,290,200,20) ;
C.add(t3) ;
label7 = new JLabel(" PROFESSIONALISM ") ;
label7.setFont(f2) ;
label7.setForeground(Color.BLUE) ;
label7.setBounds(40,320,200,20) ;
C.add(label7) ;
String[] values4 = {"Excellent" , "Very Good", "Good", "Average", "Poor"};
c4 = new JComboBox(values4) ;
c4.setForeground(Color.PINK) ;
c4.setBounds(340,320,200,20) ;
C.add(c4) ;
label8 = new JLabel(" PROFESSIONALISM (your opinion) ") ;
label8.setFont(f2) ;
label8.setForeground(Color.BLUE) ;
label8.setBounds(40,350,350,20) ;
C.add(label8) ;
t4 = new JTextField() ;
t4.setFont(f2) ;
t4.setForeground(Color.PINK) ;
t4.setBounds(340,350,200,20) ;
C.add(t4) ;
label9 = new JLabel(" AFFORDABILITY ") ;
label9.setFont(f2) ;
label9.setForeground(Color.BLUE) ;
label9.setBounds(40,380,200,20) ;
C.add(label9) ;
String[] values5= {"Excellent" , "Very Good", "Good", "Average", "Poor"};
c5 = new JComboBox(values5) ;
c5.setForeground(Color.PINK) ;
c5.setBounds(340,380,200,20) ;
C.add(c5) ;
label10 = new JLabel(" QUALITY OF WORK ") ;
label10.setFont(f2) ;
label10.setForeground(Color.BLUE) ;
label10.setBounds(40,410,200,20) ;
C.add(label10) ;
String[] values6 = {"*" , "**", "***", "****", "*****"};
c6 = new JComboBox(values6) ;
c6.setForeground(Color.PINK) ;
c6.setBounds(340,410,200,20) ;
C.add(c6) ;
label11 = new JLabel("IMPROVEMENTS SUGGESTED") ;
label11.setFont(f2) ;
label11.setForeground(Color.BLUE) ;
label11.setBounds(40,450,300,20) ;
C.add(label11) ;
System.out.println("If you want to give feedback in your own words, Please write in the box given below") ;
A = new JTextArea() ;
A.setFont(f2) ;
A.setForeground(Color.BLACK) ;
A.setLineWrap(true) ;
A.setBounds(340,450,200,20) ;
C.add(A) ;
box = new JCheckBox(" Are you sure that you have to submit your Feedback form right now?");
box.setFont(f3) ;
box.setBounds(40,500,670,20) ;
C.add(box) ;
B1 = new JButton(" SUBMIT ") ;
B1.setFont(f2) ;
B1.setForeground(Color.GREEN) ;
B1.setBounds(750,500,200,20) ;
C.add(B1) ;
B1.addActionListener(this) ;
ImageIcon frameico=new ImageIcon("siteicon.png");//create an image icon
this.setIconImage(frameico.getImage());
// B = new JTextArea() ;
// B.setFont(f2) ;
// B.setForeground(Color.BLACK) ;
// B.setLineWrap(true) ;
// B.setBounds(300,275,200,20) ;
// C.add(B) ;
// msg = new JLabel(" ") ;
// msg.setFont(f2) ;
// msg.setForeground(Color.BLUE) ;
// msg.setBounds(560,150,500,500) ;
// C.add(msg) ;
setVisible(true) ;
}
public void actionPerformed(ActionEvent e){
if(box.isSelected()) {
JOptionPane.showMessageDialog(this,"Your response has been recorded");
new home(userID);
// msg.setText(" Registration Successfully !!!!!!! ") ;
// String A1= (String)c1.getSelectedItem() ;
// String A2= (String)c2.getSelectedItem() ;
// String A3= t1.getText() ;
// String A4= (String)c3.getSelectedItem() ;
// String A5= t2.getText() ;
// String A6= t3.getText() ;
// String A7= (String)c4.getSelectedItem() ;
// String A8= t4.getText() ;
// String A9=(String)c5.getSelectedItem() ;
// String A10= (String)c6.getSelectedItem() ;
// String A11= A.getText() ;
// B.setText( "\n ECO-FRIENDLYNESS : "+ A1 + "\n QUALITY OF WORK : "+ A2 + "\n DECORATION : "+ A3 + "\n ON TIME SERVICE : "+A4 + "\n FOOD ITEMS : "+A5 + "\n REGIONAL THALIS : "+A6 + "\n PROFESSIONALISM : "+A7 + "\n UNIQUE IDEAS : "+A8 + "\n SMOOTH LOGISTICS : "+A9 + "\n VALET PARKIMG : "+A10 + "\n\n Personal Written Response : "+A11) ;
}
else{
msg.setText(" please select the check box ") ;
msg.setText(" ") ;
}
}
}
class FeedbackForm{
public static void main (String[] args) {
new FeedBack() ;
}
}